"""Engine-neutral candidate mechanics for kilix-qwen-tts."""

from .surface import (
    CLI_COMMANDS,
    PROVIDER_REFUSAL,
    RUNTIME_COMMANDS,
    AudioChunk,
    AudioFormat,
    AudioStreamAssembler,
    ConsentBinding,
    JobLifecycle,
    JobState,
    PromptAudio,
    PromptBinding,
    RuntimeUnselected,
    SurfaceError,
    SynthesisResult,
    bind_prompt,
    inspect_command,
    render_wav,
    result_metadata,
)

__all__ = [
    "CLI_COMMANDS",
    "PROVIDER_REFUSAL",
    "RUNTIME_COMMANDS",
    "AudioChunk",
    "AudioFormat",
    "AudioStreamAssembler",
    "ConsentBinding",
    "JobLifecycle",
    "JobState",
    "PromptAudio",
    "PromptBinding",
    "RuntimeUnselected",
    "SurfaceError",
    "SynthesisResult",
    "bind_prompt",
    "inspect_command",
    "render_wav",
    "result_metadata",
]
